<?php echo($this->message ? 'true' : 'false'); ?>

<div class="col-md-12 col-sm-12 col-xs-12">
<div class="x_panel">
    <div class="x_title">
    <h2><i class="fa fa-search"></i> Buscar Productos <small>Seleccione un producto</small></h2>
    <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
        </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
   
    </div>
        <div class="x_content">        
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <label for="produ-code">Producto: </label>
                     <input type="text" id="produ-code" required="required" class="col-sm-12 col-xs-12">                            
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12">
                      <label for="cantidad-id">Cantidad: </label>
                      <input type="text" id="cantidad-id" required="required" class="col-md-12 col-xs-12">            
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12">
                    <button id="add-prod" type="button" class="btn btn-success">Agregar</button>                   
                </div>
            </div>
            <div class="clearfix"></div><br><br>
            <div class="col-sm-12 col-xs-12">
                <table id="table-produ" class="table table-striped table-hover dt-responsive">
                        <thead>
                            <tr>                           
                            <th>Producto</th>
                            <th>Cantidad Items</th>
                            <th>Fecha Creación</th>
                            <th>Reservas</th>                         
                            </tr>
                        </thead>                        
                        <tbody>                    
                                                      
                       </tbody>
                </table>
            </div>
             <div class="clearfix"></div><br><br>
             <div class="row">
                <div class="col-md-1 col-sm-12 col-xs-12">
                      <button id="btn-guardar-produ" type="button" class="btn btn-success">Guardar</button>                                
                </div>
                <div class="col-md-1 col-sm-12 col-xs-12">
                    <button id="btn-cancel-produ" type="button" class="btn btn-danger">Cancelar</button>                   
                </div>
             </div>
             <div class='notifications top-left'></div>
        </div>
    </div>
</div>
<?php 
$this->inlineScript()->appendFile($this->basePath('/scripts/ventas.js'), 'text/javascript');
?>
