<div class="col-md-12 col-sm-12 col-xs-12">
<div class="x_panel">
    <div class="x_title">
    <h2><i class="fa fa-plus"></i> Iniciar Ventas <small>Cree una nueva venta</small></h2>
    <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
        </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
    </ul>
    <div class="clearfix"></div>
   
    </div>
    <div class="x_content">
 <button id="add-btn" type="submit" class="btn btn-success">Agregar</button>
</div>
</div>

</div>


<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Ventas Creadas<small>Listado con todas las ventas creadas por ud</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                      Acá podra encontrar un listado con todas las ventas que ud. haya participado. 
                    </p>
					
                    <table id="dt-lista-ventas" class="table table-striped table-hover dt-responsive" cellspacing="1" width="100%">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>PO</th>
                          <th>Fecha Creación</th>
                          <th>Fecha Compra</th>
                          <th>Fecha Entrega</th>
                          <th>Cotización</th>
                        </tr>
                      </thead>
                      <tbody>                       
                      </tbody>
                    </table>	
                </div>
            </div>
        </div>
<?php 
$this->inlineScript()->appendFile($this->basePath('/scripts/ventas.js'), 'text/javascript');
?>
