<?php $usuarios = $this->Usuarios;
$idDelUser;
?> 
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2><i class="fa fa-plus"></i> Mantenedor de Usuarios <small>Le permitirá administrar los usuarios del sistema</small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings 1</a>
                        </li>
                        <li><a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>

        </div>
        <div class="x_content">
            <form class="form-horizontal form-label-left" novalidate>

                <p>Panel de configuracion para los usuarios del sistema.  </p>
                <span class="section">Información Personal</span>

                <div class="item form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nombre <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="name" placeholder="Nombre y Apellido(s) e.j Jon Doe" required="required" type="text">
                    </div>
                </div>
                <div class="item form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="run">Run <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="run" name="run" class="form-control col-md-7 col-xs-12" data-validate-length-range="10" data-validate-words="1" placeholder="12333444-5" required="required" type="text">
                    </div>
                </div>                      
                <div class="item form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nick">Nombre Usuario <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="text" id="nick" name="nick" required="required"  class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="item form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="rol">Rol <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select id="role" class="form-control col-md-7 col-xs-12" required="required">
                            <option value="">Seleccionar...</option>                            
                        </select>                          
                    </div>
                </div>                      
                <div class="item form-group">
                    <label for="password" class="control-label col-md-3">Password</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="password" type="password" name="password" data-validate-length="6,8" class="form-control col-md-7 col-xs-12" required="required">
                    </div>
                </div>
                <div class="item form-group">
                    <label for="password2" class="control-label col-md-3 col-sm-3 col-xs-12">Repeat Password</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input id="password2" type="password" name="password2" data-validate-linked="password" class="form-control col-md-7 col-xs-12" required="required">
                    </div>
                </div>
                <input id="id-user" style="display: none" />
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Cancelar</button>
                        <button id="send-urs" type="button" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>
<div class="clearfix"></div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">
            <div class="row">
                <!--Inicio Usuarios-->
                <?php foreach ($usuarios as $usuario){ ?>
                <div class="col-md-4 col-sm-4 col-xs-12 profile_details">
                    <div class="well profile_view">
                        <div class="col-sm-12">
                            <h4 class="brief"><i><?php echo $usuario['Role']; ?></i></h4>
                            <div class="left col-xs-7">
                                <h2><?php echo $usuario['Nombre']; ?></h2>
                                <p><strong>Nombre Usuario: </strong><?php echo $usuario['Nick']?></p>
                                <ul class="list-unstyled">
                                    <li><p><i class="fa fa-asterisk"></i><strong> Run:</strong><?php echo $usuario['Rut']; ?></p></li>
                                </ul>
                            </div>
                            <div class="right col-xs-5 text-center">
                                <img src='<?php echo $this->basePath('img/user.png') ?>' alt="" class="img-circle img-responsive">
                            </div>
                        </div>
                        <div class="col-xs-12 bottom text-center">
                            <div class="emphasis">
                                <button id="<?php echo $usuario['ID']; ?>" type="button" class="btn btn-info btn-xs" value="<?php echo $usuario['ID']; ?>" > 
                                  <i class="fa fa-edit"> </i> Editar 
                              </button>
                              <button id="<?php echo 'del-'.$usuario['ID']; ?>" type="button" class="btn btn-danger btn-xs" value="<?php echo $usuario['ID']; ?>" >
                                <i class="fa fa-minus-circle"> </i> Eliminar
                              </button>
                            </div>
                        </div>
                    </div>
                </div>
                <?php }?>
                <!--Fin Usuarios-->
            </div>
        </div>          
    </div>        
</div>
 
<div id="del-user" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">   

    <div class="modal-dialog modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">Eliminar Usuario</h4>
            </div>
            <div class="modal-body">                
                <div id="userIdDel"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button id="btn-eliminar-urs" type="button" class="btn btn-danger">Eliminar</button>
            </div>

        </div>
    </div>
</div>

<?php
$this->inlineScript()->appendFile($this->basePath('/js/validator.js'), 'text/javascript');
$this->inlineScript()->appendFile($this->basePath('/scripts/usuarios.js'), 'text/javascript');
?>