<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= require_once('meta.phtml'); ?>
        <!-- Le styles -->
        <?= require_once('css.phtml'); ?>
        <!-- Scripts -->
        <?= require_once('js.phtml');?>
    </head>
    <body class="nav-md">        
       <div class="container body">
         <div class="main_container">
          <?= require_once("left-menu.phtml") ?>
          <?= require_once("header.phtml") ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by ARIAKA Ltd. Todos los derechos reservados.</p>
            </footer>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
